### PR TITLE
domains crud api created

### PR DESCRIPTION
**Pull request by daja0923**
Api implemented to domains CRUD and DNS records checkup

### CODE REVIEW

**Comment by willpower232** [comment]
Thanks for your efforts.

I'm not sure how atech would want to handle verification given that there is functionality for the users to have to verify new domains with DNS records but this is a great start.

**Comment by daja0923** [comment]
@willpower232 Thanks for the comment and labelling the PR. We are actually already using this feature. We are using postal to serve our clients. We need the api for dynamic account setup for our clients. Can't give them direct access to the postal server.

**Comment by ericringring** [comment]
Hello, could you please provide some guidelines or documentation on how to use the API for CRUD operations for the domains.

I'm doing some testing in Postman and I can only get 400 when I try to reach any of these endpoints :

  url_create = "/api/v1/domains/create"
  url_query = "/api/v1/domains/query"
  url_check = "/api/v1/domains/check"
  url_delete = "/api/v1/domains/delete"

**Comment by adamcooke** [comment]
I am planning on adding a new API with this functionality at some point in the not too distant future. In light of this, I won't merge this as it will just add another API to maintain.

**Comment by PrabhuShanmughapriyan** [comment]
Please add this feature. We absolutely need it

**Comment by casualmatt** [comment]
@adamcooke, I recall that you announced the release of the new API around the time of the Postal Two update. Could you clarify whether the new v2 API is still being developed or if it is only an internal feature for Krystal? Furthermore, do you think it would be possible to implement the CRUD API as a beta/experimental feature in the meantime? Thank you.

**Comment by yk-sgr** [comment]
Any updates?

**Comment by adamcooke** [comment]
A new API will be coming in the future.

**Pull request closed without merging**
