### PR TITLE
availability to warm up ip addresses in a pool

### PR DESCRIPTION
**Pull request by wtom**
This gives an availability to warm up ip addresses in a pool by setting a priority.

For example i send 5000 mails an hour and i want to warm up a new ip address by sending 1 an hour, then i set the priority of the main ip address on 4999 and the new one gets 1.
On the second day, i set it then to 500 and 1, for example, to send 10 times more emails with the new ip address, and so on and on.

It's still random and not guaranteed that the new one will send 1 email, but the possibility is there.

### CODE REVIEW

**Comment by masihfathi** [comment]
i think it is good to add probability option for IP, which can be planable based on day, weeks and month limit

**Comment by losingle** [comment]
In the actual transmission, the priority is not enough, and the IP frequency control should be added.

**Comment by catphish** [comment]
I just had to move one of my postal installs to a new location. Some recipients seem particularly difficult about this. This request will be getting some love!

**Comment by adamcooke** [comment]
This has now been replaced by #1422.

**Pull request closed without merging**
