### PR TITLE
fixes for link conversion

### PR DESCRIPTION
**Pull request by willpower232**
This satisfies all suggested links from https://github.com/atech/postal/issues/115 in HTML messages.

Most links are satisfied in plain text messages EXCEPT for (http://somesite.com) as the brackets cause the regex to miss.

A potential complete solution would be two regular expressions but I'm not sure thats the most maintainable. One would hope that most replaced links are in HTML messages.

### CODE REVIEW

**Comment by catphish** [comment]
I'll have a look through this as soon as I can.

**Comment by mattmartincouk** [comment]
These seem to work well! Thanks @willpower232.

**Comment by fullpipe** [comment]
Hello, when is it possible to merge?

**Comment by fullpipe** [comment]
Could it be merged?

**Comment by catphish** [comment]
That's a good question. I'll try to do some testing and merging very soon.

**Comment by afanjul** [comment]
Hi @willpower232 I have upgraded the whole postal just to "apply" this fix, but surprisingly I wasn't pushed to the master (ouch!!) So I have to apply the patch directly in the source code. After that I did "postal restart", and send a test, but sadly the fix didn't work, because a link like this:

> https://www.example.com/?utm_source=test&utm_medium=test&utm_campaign=test 

was converted to this:

> https://www.example.com/?utm_source=test&amp;utm_medium=test&amp;utm_campaign=test

so... any other solution? Did I miss something?

**Comment by willpower232** [comment]
@afanjul it looks like your system is HTML encoding the links before they get to Postal. Ordinarily that wouldn't be a problem however as the link is stored separately, you will need to turn this feature off or add notrack to the link to stop it being click tracked

**Comment by willpower232** [comment]
The benefit is just making sure a link has been clicked, something which is useful when dealing with end users.

There isn't any graph or reporting on it at the minute. Postals main focus isn't on marketing.

**Comment by dragoangel** [comment]
Why this still doesn't merged? I doesn't see any blockers.

**Comment by alkanna** [comment]
Hello @willpower232 we are still having issues with dashes and underscores in our links that are being stripped by the url parser.
Any advice?

**Pull request merged**
