### PR TITLE
Add reply_to in JSON API

### LINKED ISSUE #849: Allow access to "reply_to" header in JSON API
## Background on issue
* We use Google Groups to forward `googlegroup@mydomain.com` to `xyz@postal-route.com`
* Google Groups needs to modify the `from` header when it forwards any Yahoo emails  because of Yahoo's DMARC policy (which is set to reject everything)

## How this affects Postal
* When we receive an email from the Google Group, all Yahoo emails are coming in as:
```
From: googlegroup@mydomain.com
Reply-to: person@yahoo.com
```

## The problem
* The JSON API does not support the `reply-to` header

This is the full JSON that we are receiving:
```
{
  "attachment_quantity": 0,
  "attachments": [],
  "bounce": false,
  "cc": null,
  "date": "Wed, 17 Jul 2019 17:14:17 +0000",
  "from": "'Yahoo User' via Google Group <googlegroup@mydomain.com>",
  "html_body": "<html><head></head><body><div class=\"yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div dir=\"ltr\" data-setdir=\"false\">This is from Yahoo</div></div></body></html>",
  "id": 567,
  "in_reply_to": null,
  "mail_from": "googlegroup+bncBCGJFEGK6MERBY5PXXUQKGQECME7I5I@mydomain.com",
  "message_id": "1432602568.1595848.1563383657533@mail.yahoo.com",
  "plain_body": "This is from Yahoo",
  "rcpt_to": "googlegroup@mydomain.com",
  "received_with_ssl": true,
  "references": "<1432602568.1595848.1563383657533.ref@mail.yahoo.com>",
  "replies_from_plain_body": null,
  "size": "10163",
  "spam_status": "NotSpam",
  "subject": "Yahoo Email Test",
  "timestamp": 1563383779.555277,
  "to": "\"googlegroup@mydomain.com\" <googlegroup@mydomain.com>",
  "token": "xyz123456789"
}
```

## Proposed solution
* The JSON API should be extended to support the `reply-to` header

### PR DESCRIPTION
**Pull request by danpastori**
I extended the JSON API to allow access to the `reply-to` mail header. This fixes #849.

### CODE REVIEW

**Comment by jaydrogers** [comment]
I cloned the `521dimensions/postal:master` branch to my test server and ran a test with this pull request active on it. Here are the results I received when I sent an email from "person@yahoo.com" to "googlegroup@mydomain.com":

```json
{
  "attachment_quantity": 0,
  "attachments": [],
  "auto_submitted": null,
  "bounce": false,
  "cc": null,
  "date": "Thu, 18 Jul 2019 01:22:38 +0000",
  "from": "'Yahoo User' via Google Group <googlegroup@mydomain.com>",
  "html_body": "<html><head></head><body><div class=\"yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div dir=\"ltr\" data-setdir=\"false\">This is from Yahoo</div></div></body></html>",
  "id": 18,
  "in_reply_to": null,
  "mail_from": "googlegroup+bncBCGJFEGK6MERBYMTX7UQKGQEDVJKR6A@mydomain.com",
  "message_id": "810226113.1764128.1563412958923@mail.yahoo.com",
  "plain_body": "This is from Yahoo",
  "rcpt_to": "googlegroup@mydomain.com",
  "received_with_ssl": true,
  "references": "<810226113.1764128.1563412958923.ref@mail.yahoo.com>",
  "replies_from_plain_body": null,
  "reply_to": [
    "Yahoo User <person@yahoo.com>"
  ],
  "size": "10128",
  "spam_status": "NotSpam",
  "subject": "Test Postal Update #1",
  "timestamp": 1563412963.5554078,
  "to": "\"googlegroup@mydomain.com\" <googlegroup@mydomain.com>",
  "token": "abcd1234"
}
```

This looks perfect for what we are looking for.

**Comment by danpastori** [comment]
I didn't like how the reply to was coming back as an array so I updated it to be a string.

**Comment by jaydrogers** [comment]
Looks great! Running my tests on my server with this change yields these results:

```json
{
  "attachment_quantity": 0,
  "attachments": [],
  "bounce": false,
  "cc": null,
  "date": "Thu, 18 Jul 2019 17:18:24 +0000",
  "from": "'Yahoo User' via Google Group <googlegroup@mydomain.com>",
  "html_body": "<html><head></head><body><div class=\"yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div dir=\"ltr\" data-setdir=\"false\">This is my message from Yahoo</div></div></body></html>",
  "id": 571,
  "in_reply_to": null,
  "mail_from": "googlegroup+bncBCGJFEGK6MERB6OQYLUQKGQETMSD5LA@521dev.co",
  "message_id": "1344476306.1966138.1563469944436@mail.yahoo.com",
  "plain_body": "This is my message from Yahoo",
  "rcpt_to": "googlegroup@mydomain.com",
  "received_with_ssl": true,
  "references": "<1344476306.1966138.1563469944436.ref@mail.yahoo.com>",
  "replies_from_plain_body": null,
  "reply_to": "Yahoo User <person@yahoo.com>",
  "size": "10136",
  "spam_status": "NotSpam",
  "subject": "Array Test",
  "timestamp": 1563469947.722922,
  "to": "\"googlegroup@mydomain.com\" <googlegroup@mydomain.com>",
  "token": "abcd1234"
}
```

The `reply_to` is no longer an array.

**Comment by adamcooke** [comment]
`Reply-to` can contain multiple addresses so I do believe this should be returning an array rather than a string, I'm afraid.

**Comment by jaydrogers** [comment]
Good catch @adamcooke! I wasn't aware that you could set multiple "reply-to" emails, but it makes total sense. I reverted that change, so it is now back to this:

```json
{
  "attachment_quantity": 0,
  "attachments": [],
  "auto_submitted": null,
  "bounce": false,
  "cc": null,
  "date": "Thu, 18 Jul 2019 01:22:38 +0000",
  "from": "'Yahoo User' via Google Group <googlegroup@mydomain.com>",
  "html_body": "<html><head></head><body><div class=\"yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div dir=\"ltr\" data-setdir=\"false\">This is from Yahoo</div></div></body></html>",
  "id": 18,
  "in_reply_to": null,
  "mail_from": "googlegroup+bncBCGJFEGK6MERBYMTX7UQKGQEDVJKR6A@mydomain.com",
  "message_id": "810226113.1764128.1563412958923@mail.yahoo.com",
  "plain_body": "This is from Yahoo",
  "rcpt_to": "googlegroup@mydomain.com",
  "received_with_ssl": true,
  "references": "<810226113.1764128.1563412958923.ref@mail.yahoo.com>",
  "replies_from_plain_body": null,
  "reply_to": [
    "Yahoo User <person@yahoo.com>"
  ],
  "size": "10128",
  "spam_status": "NotSpam",
  "subject": "Test Postal Update #1",
  "timestamp": 1563412963.5554078,
  "to": "\"googlegroup@mydomain.com\" <googlegroup@mydomain.com>",
  "token": "abcd1234"
}
```

Can we also submit a pull request to update the API documentation as well? It would be great to have this documented.

**Pull request merged**
