### PR TITLE
added missing 'tzinfo-data' gem depend

### PR DESCRIPTION
**Pull request by rcmorano**

### CODE REVIEW

**Comment by catphish** [comment]
Is there a context / reason for this?

**Comment by rcmorano** [comment]
Of course, I had problems when starting postal without this dependency:

```
16:34:52 web.1           | => ! Unable to load application: TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
16:34:52 web.1           | => /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:22:in `rescue in block in <class:Railtie>': tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install (TZInfo::DataSourceNotFound)
...
16:34:53 smtp.1          | => D, [2017-12-05T16:34:53.161641 #28672] DEBUG -- sentry: ** [Raven] tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install excluded from capture due to environment or should_capture callback
16:34:53 smtp.1          | => rake aborted!
16:34:53 smtp.1          | => TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
16:34:53 smtp.1          | => /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:22:in `rescue in block in <class:Railtie>'
...
16:34:53 worker.1        | => /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:22:in `rescue in block in <class:Railtie>': tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install (TZInfo::DataSourceNotFound)
16:34:53 worker.1        | => 	from /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:19:in `block in <class:Railtie>'
...
16:34:53 cron.1          | => D, [2017-12-05T16:34:53.252156 #28670] DEBUG -- sentry: ** [Raven] tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install excluded from capture due to environment or should_capture callback
16:34:53 cron.1          | => rake aborted!
16:34:53 cron.1          | => TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
16:34:53 cron.1          | => /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:22:in `rescue in block in <class:Railtie>'
...
16:34:53 requeuer.1      | => D, [2017-12-05T16:34:53.387986 #28674] DEBUG -- sentry: ** [Raven] tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install excluded from capture due to environment or should_capture callback
16:34:53 requeuer.1      | => rake aborted!
16:34:53 requeuer.1      | => TZInfo::DataSourceNotFound: tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install
16:34:53 requeuer.1      | => /opt/postal/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:22:in `rescue in block in <class:Railtie>'
```

**Comment by willpower232** [comment]
can you confirm what OS and version you're using? I've tried a few installs in the recent months and never bumped into this :-P

**Comment by rcmorano** [comment]
Aloha @willpower232,

I get those errors while trying to run postal on our [docker container](https://github.com/Emergya/docker-postal/blob/master/Dockerfile). 
Maybe some base depend is missing on our system that replaces the need for the "tzinfo-data" functionality, but since adding that gem was the message I received and it worked, I opened the PR :)

Thanks!

**Comment by arashm** [comment]
`tzinfo-data` is required by `sentry-raven` in case the operating system doesn't provide timezone data. On Ubuntu you need to install `tzdata` package for it to work (which is not pre-installed in docker).

**Comment by lukasmrtvy** [comment]
same applies also for Alpine OS.  Merge?

**Pull request closed without merging**
