### PR TITLE
update install scripts with new official rabbitmq location

### PR DESCRIPTION
**Pull request by willpower232**
As discussed in #1294

### CODE REVIEW

**Review by nhCoder — APPROVED** [review]

**Review by nhCoder — APPROVED** [review]

**Comment by JaiBansal24** [comment]
Hi,
 (Note:   I have no knowledge of this type of scripts, so pls excuse)

I have no clue what to do with update so I ran all the commands (one by one, in correct sequence), respectively in fresh Ubuntu 16 and 18.
Loads of errors came in both.
Used 2 fresh VPS on DO.

Even SSH putty kept crashing on step 29 apt update of Ubuntu 16.04 x64

on Ubuntu 18 :
root@pos-10:~# apt install -y ruby2.3 ruby2.3-dev build-essential libssl-dev mariadb-server libmysqlclient-dev rabbitmq-server nodejs git nginx wget nano
Reading package lists... Done
Building dependency tree
Reading state information... Done
nano is already the newest version (2.9.3-2).
nano set to manually installed.
wget is already the newest version (1.19.4-1ubuntu2.2).
wget set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rabbitmq-server : Depends: erlang-base (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            erlang-base-hipe (>= 1:21.3) but it is not going to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-crypto (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-eldap (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-inets (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-mnesia (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-os-mon (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-parsetools (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-public-key (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-runtime-tools (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-ssl (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-syntax-tools (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-tools (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
                   Depends: erlang-xmerl (>= 1:21.3) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or
                            esl-erlang (>= 1:21.3) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by willpower232** [comment]
@JaiBansal24 thanks for letting me know, I didn't need erlang in my testing but apparently you do so I've added it to the scripts in this PR. You should be able to try again however there is currently a ruby problem which will prevent installation (#1324)

**Comment by wh4u** [comment]
On a fresh ubuntu16 installation the erlang packages still have issues

The following packages have unmet dependencies:
 rabbitmq-server : Depends: erlang-crypto (>= 1:21.3) or
                            esl-erlang (>= 1:21.3)
                   Depends: erlang-crypto (< 1:24.0) or
                            esl-erlang (< 1:24.0)
                   Depends: erlang-eldap (>= 1:21.3) but it is not going to be installed or
                            esl-erlang (>= 1:21.3)
                   Depends: erlang-eldap (< 1:24.0) but it is not going to be installed or
                            esl-erlang (< 1:24.0)
                   Depends: erlang-inets (>= 1:21.3) or
                            esl-erlang (>= 1:21.3)
                   Depends: erlang-inets (< 1:24.0) or
                            esl-erlang (< 1:24.0)
                   Depends: erlang-os-mon (>= 1:21.3) or
                            esl-erlang (>= 1:21.3)
                   Depends: erlang-os-mon (< 1:24.0) or
                            esl-erlang (< 1:24.0)
                   Depends: erlang-public-key (>= 1:21.3) or
                            esl-erlang (>= 1:21.3)
                   Depends: erlang-public-key (< 1:24.0) or
                            esl-erlang (< 1:24.0)
                   Depends: erlang-ssl (>= 1:21.3) or
                            esl-erlang (>= 1:21.3)
                   Depends: erlang-ssl (< 1:24.0) or
                            esl-erlang (< 1:24.0)
E: Unable to correct problems, you have held broken packages.

**Comment by willpower232** [comment]
@wh4u I can't reproduce that I'm afraid, do you definitely have the version I updated yesterday with packages.erlang-solutions.com?

Alternatively you might have to look higher up in the output to see if there was any problem completing `apt update`

**Comment by wh4u** [comment]
> @wh4u I can't reproduce that I'm afraid, do you definitely have the version I updated yesterday with packages.erlang-solutions.com?
i have this commit
https://github.com/postalhq/postal/pull/1310/commits/116b5e7e192874f626875d23e922a8d0d18c51da

**Comment by willpower232** [comment]
Then there may be an error in the output before you reached that point. Are you able to spot anything or include a copy here?

**Comment by wh4u** [comment]
i used a fresh installation of ubuntu18 and it proceeded without errors until i reached the point of mimemagic

**Comment by willpower232** [comment]
good, thats as far as it can get currently :sweat_smile:

**Comment by abdallahtaleb** [comment]
Any idea when this issue would be solved? (locked to mimemagic (0.3.5))

**Comment by JaiBansal24** [comment]
Hi guys,
Any workable update now ?

I was wondering if a copy of the previously working Ruby can be placed on any external server and just the Ruby source path be modified, in the previously working script 

Maybe that can be a workaround for the time being ?

Rgds,
Jai

**Comment by willpower232** [comment]
To confirm, the Ruby mimemagic issue is unrelated to the overall topic of this PR.

Regarding your question, it is not recommended to manage the downloaded dependency files yourself as it will likely cause issues in your future but if you have a working copy of them that you want to duplicate, nothing can stop you.

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by arall** [comment]
> To confirm, the Ruby mimemagic issue is unrelated to the overall topic of this PR.

I think adding:
```
cd /opt/postal/app
bundle update rails
```
Before `postal bundle /opt/postal/vendor/bundle`, should fix the mimemagic issue.

**Comment by akalantari** [comment]
I found this answer https://stackoverflow.com/a/66921259 that fixes the mimemagic installation problem

**Pull request closed without merging**
