### PR TITLE
Routes CRUD api added.

### PR DESCRIPTION
**Pull request by rezaxd**
Hey there!
Just wrote api for Routes (Routes, http endpoints, smtp endpoints and address endpoints).
Note: For domain api used from @daja0923 's PR (my thx to you.). #992

### CODE REVIEW

**Comment by Igcorreia** [comment]
Dear @rezaxd I just posted an [issue ](https://github.com/postalhq/postal/issues/1142) and then noticed this. Just wanted to say thank you. :)

**Comment by Igcorreia** [comment]
Is there any reason why this still open? This is the reason I am looking to use PostalHQ, can you guys please accept this pull?

**Comment by willpower232** [comment]
Unfortunately only Krystal staff can merge so if you need this work, you could try using a git cloned copy of Postal instead of the regular install.

**Comment by Igcorreia** [comment]
@rezaxd I just tried to add your PR (locally) and restarted Postal, your endpoint should be like:
/v1/api/domains/domain correct? Can't seem to get them working for some reason. your PR says that 12 files where changed correct? should be enough to get them working correctly? Thanks in advanced

**Comment by Igcorreia** [comment]
> @rezaxd I just tried to add your PR (locally) and restarted Postal, your endpoint should be like:
> /v1/api/domains/domain correct? Can't seem to get them working for some reason. your PR says that 12 files where changed correct? should be enough to get them working correctly? Thanks in advanced



> Hey there!
> Just wrote api for Routes (Routes, http endpoints, smtp endpoints and address endpoints).
> Note: For domain api used from @daja0923 's PR (my thx to you.). #992

Worked Perfectly!

**Comment by dragoangel** [comment]
> Unfortunately only Krystal staff can merge so if you need this work, you could try using a git cloned copy of Postal instead of the regular install.

Is this an issue?

**Comment by ipatka** [comment]
I would also like to see this merged. Does it just need to be reviewed by a maintainer? cc @catphish

**Comment by catphish** [comment]
Thank you for contributing this. We're very sorry we haven't had a chance to review this yet. We're catching up, but this is of course a fairly large chunk of code to review.

**Comment by rezaxd** [comment]
@catphish Thank u.

**Comment by adamcooke** [comment]
I am planning on adding a new API with this functionality at some point in the not too distant future. In light of this, I won't merge this as it will just add another API to maintain. 

Thank you though.

**Pull request closed without merging**
