### PR TITLE
IP authentication backend

### PR DESCRIPTION
**Pull request by catphish**
Adds support to authenticate to SMTP based on the source IP address rather than using any credentials.

### CODE REVIEW

**Comment by yomiit** [comment]
@catphish and @adamcooke Greetings.

I updated my install with the recent commit. I am trying to use this feature without success. I added a "SMTP-IP" credential with the server I want to connect without authentication as well as configure necessary IP Rules for the sending domain. I keep getting "530 Authentication required".

Checking my logs, this error shows immediately after RCPT TO command.

Any suggestion on how to use this feature? Other credential types works fine.

**Comment by yomiit** [comment]
I figured this out.  I had to kill an old smtp process that was not stopped/restarted using normal "postal restart".

**Comment by catphish** [comment]
> I figured this out. I had to kill an old smtp process that was not stopped/restarted using normal "postal restart".

Thanks for the update. I couldn't think of any other obvious reasons this would fail :+1:

**Comment by nenominal** [comment]
Hi,

I've updated to the latest version but I haven't figured where do I need to configure it on server side so I can enable and filter. Could someone point me to right direction, please!

Thanks.

**Comment by willpower232** [comment]
I believe this is still handled in the credential area, you can now set the type of credential to be `SMTP-IP`

**Comment by nenominal** [comment]
Yep, I found it, when I create a new user there is a drop-down with SMTP-IP option.
Is it possible to use only IP validation and not users/password? (some sort of whitelist)

**Comment by willpower232** [comment]
if you change the dropdown to `SMTP-IP` you will see the key field is replaced by a network field so you can achieve this allow list functionality

**Comment by nenominal** [comment]
I think I hit a bug or there is something I need to do and I'm not aware off.
As you can see, in the console for the new credential I added the key and network field have the same value.
In the database there is no network field.

I've tried to use it but it doesn't work and there are no logs in postal that can help me...

pma
postal

**Pull request merged**
